#!/system/bin/sh

L="log -p i -t SELinuxLabel"

# Bail out early if not on a SELinux build
getprop ro.build.selinux | grep -q 1 || exit
if [ ! -f /file_contexts ]; then
  exit
fi

LABELDATA=0
LABELSYS=0
LABELDALVIKCACHE=0

# Test for broken app_process
ls -Zd /system/bin/app_process | grep -q zygote
if [ $? -eq 1 ]; then
  $L "fixing app_process..."
  mount -o remount,rw /system
  restorecon /system/bin/app_process
  mount -o remount,ro /system
fi
